### ISSUE TITLE
module 'keras_tuner.oracles' has no attribute 'BayesianOptimization' (Cassini-CDA)

### ISSUE THREAD

**Issue by fredifqh** [ThomasAlbin/Astroniz-YT-Tutorials#65] opened 2023-05-14 01:40 UTC
I get the following error in the section Machine Learning Training: 

AttributeError                            Traceback (most recent call last)
Cell In[13], line 58
     54         self.oracle.update_trial(trial.trial_id, {'val_loss': np.mean(val_losses)})
     56 # Build up the Tuner
     57 tuner = CVTuner(hypermodel=build_model,
---> 58                 oracle=keras_tuner.oracles.BayesianOptimization(
     59                     objective='val_loss',
     60                     max_trials=50),
     61                 overwrite=True,
     62                 project_name="CDA_IID_Calibration")

AttributeError: module 'keras_tuner.oracles' has no attribute 'BayesianOptimization'

**Comment by ThomasAlbin** [comment] 2023-05-14 12:01
Hey there! That is strange. What keras_tuner version do you have? You can simply print it via:

`import keras_tuner
print(keras_tuner.__version__)`

In my tutorials we use version 1.1.2. I just cross-checked it and was not able to reproduce the issue

**Comment by fredifqh** [comment] 2023-05-14 12:29
Dear Thomas, thanks for your answer.

In fact, the problem was the keras_tuner version. I got the error with 1.3.5 version. I installed version 1.1.2 and now it is working.

**Comment by ThomasAlbin** [comment] 2023-05-14 12:36
Thanks for the update! Hmmm am I THAT outdated? I should check the versioning.

Thanks again. I'd close this issue now

**Closed by ThomasAlbin** 2023-05-14 12:36 UTC
